import Head from 'next/head'
import { Inter } from 'next/font/google'
import { BsFillMoonStarsFill, BsChevronDoubleDown, BsBoxArrowInUpRight, BsWhatsapp, BsFillSunFill } from "react-icons/bs"
import { SiGmail } from "react-icons/si"
import { AiFillLinkedin, AiFillFacebook, AiFillTwitterCircle, AiFillGithub } from "react-icons/ai"
import Image from 'next/image'
import logo from "../../public/logo.png"
import deved from "../../public/dev-ed-wave.png"
import e_commerce from "../../public/E-commerce.png"
import Waddy from "../../public/Waddy.png"
import Furniture from "../../public/Furniture.jpg"
import { useState } from 'react'
export default function Home() {
  const [theme , setTheme] = useState("light")
  return (
    <div>
      <Head>
        <title>Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=' bg-white' id={theme === "dark" ? "darkmood" : undefined}>
        <section className=' min-h-screen px-10'>
          <nav className='p-3 mb-12 flex justify-between'>
            <div>
              <Image src={logo} alt='logo' className='w-10 h-auto' />
            </div>
            <ul className='flex items-center'>
              <li>
                {theme === "light" ? <BsFillMoonStarsFill className='cursor-pointer text-xl' onClick={() => {
                  setTheme("dark")
                }} /> : <BsFillSunFill className='cursor-pointer text-xl text-white
                ' onClick={() => {
                      setTheme("light")
                    }} />}
              </li>
              <li>
                <a onClick={() => {
                  var link = document.createElement('a');
                  link.href = 'http://localhost:3000/CV.pdf';
                  link.download = 'CV.pdf';
                  document.body.appendChild(link);
                  link.click();
                  document.body.removeChild(link);
                }} className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'>Resume</a>
              </li>
            </ul>
          </nav>
          <div className='px-5 text-center'>
            <h2 className='text-4xl pb-3 text-teal-500 font-semibold'>Hi I&apos;m Omar Naguib</h2>
            <h3 className='text-xl pb-3' id={theme === "dark" ? "darkmood-color" : undefined} >Full Stack  Developer . </h3>
            <p className='text-md pb-2 leading-8 text-gray-800' id={theme === "dark" ? "darkmood-color" : undefined}>Freelancer Services For Programming needs.</p>
            <p className='text-md pb-2 text-gray-800' id={theme === "dark" ? "darkmood-color" : undefined}>Let&apos;s Go For Discover More About Me <BsChevronDoubleDown className='inline text-teal-500 animate-bounce text-md' /> </p>
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-400 rounded-full w-80 h-80 '>
            <Image src={deved} alt='deved' className='pt-5' />
          </div>
          <div className='flex justify-center text-3xl gap-8 pb-4'>
            <a href='https://www.facebook.com/omarmmohhammedd' target='_blank' className='text-blue-600'><AiFillFacebook /></a>
            <a href='https://www.linkedin.com/in/omar-mohammed-756b14241/' target='_blank' className='text-blue-500'><AiFillLinkedin /></a>
            <a href='https://twitter.com/omar__naguib' target='_blank' className='text-blue-500'><AiFillTwitterCircle /></a>
            <a href='https://github.com/omarmmohhammedd' target='_blank'><AiFillGithub id={theme === "dark" ? "darkmood-color" : undefined} /></a>
          </div>
        </section>
        <section className=' py-2  px-10 border-t-2 pb-10'>
          <div className='p-6'>
            <div className='grid md:grid-cols-2 gap-x-10 gap-y-20 '>
              <div className='flex-col'>
                <h3 className='text-3xl pb-2 text-teal-600'>Education </h3>
                <div className='text-md  p-4 leading-8 text-white bg-teal-600 rounded-lg h-full flex items-center' id={theme === "dark" ? "darkmood-color-cards" : undefined} >
                  I&apos;m Graduated From Higher Technological Institute In 2023 Computer Science Department With Very Good Grade And Degree Of Graduate Project is Excellent
                </div>
              </div>
              <div className='flex-col'>
                <h3 className='text-3xl pb-2 text-blue-400'>About Me </h3>
                <div className=' p-4  leading-8 text-white bg-blue-400 rounded-lg h-full  flex items-center ' id={theme === "dark" ? "darkmood-color-cards" : undefined} >
                  <p>Since The Beginning Of My Journey As A Freelancer Developer in 2021
                    I&apos;v Done Remote Work For Various Clients Developing Scalable, Performant And Secure Web Applications using
                    <span className='text-slate-700 font-semibold'> Node JS </span>,
                    <span className='text-slate-700 font-semibold'> Express JS </span> ,
                    <span className='text-slate-700 font-semibold'> React JS </span>
                    And <span className='text-slate-700 font-semibold'> Mongo DB </span>.
                  </p>

                </div>
              </div>
              <div className='flex-col '>
                <h3 className='text-3xl pb-2 text-blue-400'>Technical  Skills </h3>
                <div className='px-4 leading-8 text-white bg-blue-400 rounded-lg  h-full flex flex-col items-start justify-around md:flex-row md:items-center' id={theme === "dark" ? "darkmood-color-cards" : undefined} >
                  <ol className='list-decimal'>
                    <h4 className='text-slate-700 font-semibold '>Front-End</h4>
                    <li className='ml-4'> HTML5 </li>
                    <li className='ml-4'> CSS </li>
                    <li className='ml-4'> Tailwind CSS </li>
                    <li className='ml-4'> React JS </li>
                    <li className='ml-4'>Next JS</li>
                    <li className='ml-4'> TypeSript </li>
                  </ol>
                  <ol className='list-decimal'>
                    <h4 className='text-slate-700 font-semibold'>Back-End</h4>
                    <li className='ml-4'> Node.js and Express.js </li>
                    <li className='ml-4'> MongoDB , MySQL  and Postgres </li>
                    <li className='ml-4'>RESTful API and GraphQL </li>
                    <li className='ml-4'> Payment Integration </li>
                    <li className='ml-4'> Socket.IO </li>
                    <li className='ml-4'>Basic Knowledge Of Nest.js.</li>
                  </ol>
                </div>
              </div>
              <div className='flex-col'>
                <h3 className='text-3xl pb-2 text-teal-600'>Personal Skills</h3>
                <ol className=' p-4 px-7 leading-8 text-white bg-teal-600 rounded-lg h-full list-decimal flex flex-col items-start justify-center' id={theme === "dark" ? "darkmood-color-cards" : undefined} >
                  <li> Experience Working With Remote Teams</li>
                  <li > I Can Bring Value To Your Organization By Providing You With Top-Notch Node.js Development Services</li>
                  <li> Committed To Delivering High-Quality Work That Meets The Needs Of My Clients </li>
                </ol>
              </div>
            </div>
          </div>
        </section>
        <section className='py-4 px-10 border-t-2  bg-slate-100 flex-col justify-center items-center' id={theme === "dark" ? "darkmood" : undefined}>
          <h3 className='text-3xl py-4 text-blue-400'>Latest Projects</h3>
          <div className='bg-slate-50 drop-shadow-xl p-5 rounded-xl max-w-4xl m-auto' id={theme === "dark" ? "darkmood-color-cards" : undefined} >
            <div className='grid grid-cols-1 md:grid-cols-2 gap-10 '>
              <div className=''>
                <Image src={e_commerce} alt='e-commerce' className='w-70 h-full' />
              </div>
              <div className=' flex flex-col items-start justify-center'>
                <h4 className=' text-blue-400 pb-2 text-xl md:text-lg '>Family Food</h4>
                <p className='text-gray-500 text-sm py-2' id={theme === "dark" ? "darkmood" : undefined}> Building E-commerce App For Family Company With Web Dashboard For Manager And Mobile Device For Clients That Has Advanced  Feauters Like (Payment Integration - Monthly Back Up Data - Installment And Full Cash Support - Real Time Chat  )   </p>
                  <h5 className='text-gray-600'>Technologies</h5>
                <ul className='flex  flex-wrap text-blue-400 text-sm' >
                  <li className='pr-1'> React JS | </li> 
                  <li className='pr-1'> Redux Toolkit | </li>
                  <li className='pr-1'> MUI CSS | </li>
                  <li className='pr-1'> Node JS | </li>
                  <li className='pr-1'> Express JS | </li>
                  <li className='pr-1'> Mongo DB | </li>
                  <li className='pr-1'> Flutter</li>
                </ul>
                <a href='https://github.com/omarmmohhammedd/Graduation_Project
                ' target='_blank' className='bg-gradient-to-r from-cyan-500 to-teal-500 text-center cursor-pointer text-white w-48 p-2 my-2 rounded-lg '>View On Github <BsBoxArrowInUpRight className='inline' /></a>
              </div>

            </div>
          </div>
          <div className='bg-slate-50 drop-shadow-xl p-5 rounded-xl max-w-4xl mt-4  m-auto 
          ' id={theme === "dark" ? "darkmood-color-cards" : undefined}>
            <div className='grid grid-cols-1 md:grid-cols-2 gap-10 '>
              <div className='h-full'>
                <Image src={Waddy} alt='Waddy' className='w-70 h-full' />
              </div>
              <div className=' flex flex-col items-start justify-center'>
                <h4 className=' text-blue-400 pb-2 text-xl md:text-lg '>Waddy</h4>
                <p className='text-gray-500 text-sm py-2' id={theme === "dark" ? "darkmood-color" : undefined}> Building Real Time Delivery App  For Wadyy Company With Web Dashboard For Manager And Mobile Device For Clients That Has Advanced  Feauters Like ( Payment Integration - Monthly Back Up Data - Real Time Tracking  - Real Time Chat   )   </p>
                  <h5 className='text-gray-600'>Technologies</h5>
                <ul className='flex  flex-wrap text-blue-400 text-sm'>
                  <li className='pr-1'> HTML5 | </li> 
                  <li className='pr-1'> CSS3 | </li> 
                  <li className='pr-1'> JavaScript| </li> 
                  <li className='pr-1'> Tailwind CSS | </li>
                  <li className='pr-1'> Node JS | </li>
                  <li className='pr-1'> Express JS | </li>
                  <li className='pr-1'> Mongo DB | </li>
                  <li className='pr-1'> Flutter</li>
                </ul>
                <a href='https://github.com/omarmmohhammedd/Waddy
                ' target='_blank' className='bg-gradient-to-r from-cyan-500 to-teal-500 text-center cursor-pointer text-white w-48 p-2 my-2 rounded-lg '>View On Github <BsBoxArrowInUpRight className='inline' /></a>
              </div>
            </div>
          </div>
          <div className='bg-slate-50 drop-shadow-xl p-5 rounded-xl max-w-4xl mt-4  m-auto
          ' id={theme === "dark" ? "darkmood-color-cards" : undefined}>
            <div className='grid grid-cols-1 md:grid-cols-2 gap-10 '>
              <div className='w-full'>
                <Image src={Furniture} alt='Furniture' className='w-70 h-full' />
              </div>
              <div className=' flex flex-col items-start justify-center'>
                <h4 className=' text-blue-400 pb-2 text-xl md:text-lg '>Wood-Essence</h4>
                <p className='text-gray-500 text-sm py-2'> Building Landing Page For Wood-Essence-Furniture-store With Responsive Design  For Mobile Device </p>
                  <h5 className='text-gray-600'>Technologies</h5>
                <ul className='flex  flex-wrap text-blue-400 text-sm'>
                  <li className='pr-1'> HTML5 | </li> 
                  <li className='pr-1'> CSS3 | </li> 
                  <li className='pr-1'> JavaScript </li> 
                </ul>
                <a href='https://omarmmohhammedd.github.io/Wood-Essence-Furniture-store/
                ' target='_blank' className='bg-gradient-to-r from-cyan-500 to-teal-500 text-center cursor-pointer text-white w-48 p-2 my-2 rounded-lg'>View On Github <BsBoxArrowInUpRight className='inline' /></a>
              </div>
            </div>
          </div>
        </section>
        <footer className='h-24 md:h-20 flex items-center justify-around  bg-blue-400' id={theme === "dark" ? "darkmood-footer" : undefined}>
          <h3 className='text-white font-semibold text-3xl ' id={theme === "dark" ? "darkmood-color" : undefined}>Contact Me </h3>
          <div className='flex justify w-1/3 md:justify-end '>
            <a onClick={() => {
              location.href = 'mailto:omar.mmohhammedd@gmail.com'
            }}  className='text-red-500 text-2xl px-2'><SiGmail/></a>
            <a href="https://wa.me/+201065447142" className='text-lime-300 text-2xl px-2'><BsWhatsapp /></a>
          </div>
        </footer>
      </main>
    </div>
  );
}
